version: '2.1'

networks:
  my-net:
    driver: bridge

services:
  dukat-rest:
    build: ./
    networks:
      my-net:
        aliases:
          - dukat
          - dukat.docker

    environment:
      - PYTHONPATH=/webapp
      - DB_LOCATION=/var/log/db/casm.db
      - DB_CONNECT_TMOUT=15
      #- WORKSPACE
      - LOGS=/var/log
      - SRC=/webapp

    #entrypoint: /bin/bash

    expose:
      - 4130

    volumes:
      - /tmp/docker/logs/dukat:/var/log/
